// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXmFbzcXvzp2yAqGesHLD4uALTlnTijHc',
    appId: '1:802653838357:web:23a0c6a0e4ccce4eb8821c',
    messagingSenderId: '802653838357',
    projectId: 'cmdproyect-ae457',
    authDomain: 'cmdproyect-ae457.firebaseapp.com',
    storageBucket: 'cmdproyect-ae457.firebasestorage.app',
    measurementId: 'G-WZVNYM1RTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOaDt7Vneik7N-hMxT9NwNTFvcVSkG0kw',
    appId: '1:802653838357:android:724d16c485bac9cbb8821c',
    messagingSenderId: '802653838357',
    projectId: 'cmdproyect-ae457',
    storageBucket: 'cmdproyect-ae457.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLQXDPyo3pOeJVJzytdux2YTKOciK2WzQ',
    appId: '1:802653838357:ios:7ef7538d7744510cb8821c',
    messagingSenderId: '802653838357',
    projectId: 'cmdproyect-ae457',
    storageBucket: 'cmdproyect-ae457.firebasestorage.app',
    iosBundleId: 'com.example.cmdproyect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLQXDPyo3pOeJVJzytdux2YTKOciK2WzQ',
    appId: '1:802653838357:ios:7ef7538d7744510cb8821c',
    messagingSenderId: '802653838357',
    projectId: 'cmdproyect-ae457',
    storageBucket: 'cmdproyect-ae457.firebasestorage.app',
    iosBundleId: 'com.example.cmdproyect',
  );

}